// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "hero": { "headline": string; "subtext": string; "cta": string } } };
  export const home: { "hero": { "headline": string; "subtext": string; "cta": string } };
}
